/** @type {import('next-sitemap').IConfig} */
module.exports = {
  siteUrl: "https://karmahq.xyz",
  // robots.txt is now generated by app/robots.ts
  generateRobotsTxt: false,
  // generateIndexSitemap: false,
  exclude: ["/stats", "/admin/**", "/super-admin/**", "/safe/**"],
  sitemapSize: 30000,
  robotsTxtOptions: {
    additionalSitemaps: [
      "https://karmahq.xyz/sitemaps/projects/sitemap.xml",
      "https://karmahq.xyz/sitemaps/communities/sitemap.xml",
    ],
  },
};
