/** @type {import('next-sitemap').IConfig} */
module.exports = {
  siteUrl: "https://karmahq.xyz",
  // robots.txt is now generated by app/robots.ts
  generateRobotsTxt: false,
  // generateIndexSitemap: false,
  // Static pages are owned by app/sitemap.ts — exclude them here so next-sitemap
  // only generates sitemaps for dynamic project/community pages.
  exclude: [
    "/stats",
    "/admin/**",
    "/super-admin/**",
    "/safe/**",
    "/",
    "/projects",
    "/communities",
    "/funders",
    "/funding-map",
    "/seeds",
    "/create-project-profile",
    "/knowledge",
    "/knowledge/**",
    "/privacy-policy",
    "/terms-and-conditions",
  ],
  sitemapSize: 30000,
};
