// This file contains the list of pages that are on the root of the website, as we use a
// dynamic routing system and also use /[communities], to avoid issues on SSR, we added this constant to check.
export const pagesOnRoot = [
  "my-projects",
  "stats",
  "404",
  "admin",
  "funding-map",
  "api",
  "auth",
  "project",
  "address",
  "karma-gap-patron",
  "projects",
  "communities",
  "sitemaps",
  "sitemaps",
  "_vercel",
  "super-admin",
  ".next",
  "_next",
  "chunks",
  "tx",
  "sitemaps",
  "grants",
  "v1",
  "static",
  "docs",
  "assets",
];
