const networks = [
  "Aleo",
  "Aleph Zero",
  "Bitcoin",
  "Cardano",
  "Cosmos/IBC",
  "EVM",
  "Farcaster",
  "NEAR",
  "Nouns",
  "Polkadot",
  "Ripple",
  "Solana",
  "Stellar",
  "TON",
  "Tezos",
  "Tron",
  "zCash",
];

const organizations = [
  "3327",
  "01 Exchange",
  "0x Protocol",
  "1inch Foundation",
  "4EVERLAND",
  "88mph",
  "Aave",
  "Aavegotchi",
  "Abracadabra.money",
  "Acala",
  "ACryptoS",
  "AirCoin",
  "Ajna",
  "Akash",
  "Alchemix",
  "Alchemy",
  "Aleo",
  "Aleph Zero",
  "Algofi",
  "Algorand Foundation",
  "Algovera",
  "Alien Worlds",
  "Allbridge",
  "Alpaca Finance",
  "Alpha Venture DAO",
  "Ampleforth",
  "AngelBlock",
  "Ankr",
  "ApeCoin DAO",
  "ApeSwap",
  "Aptos Foundation",
  "Aragon",
  "Arbitrum Foundation",
  "Arcana",
  "Archway",
  "ARKEN Finance",
  "Arweave",
  "AssetMantle",
  "Astar",
  "ATOM Accelerator",
  "Audius",
  "Aura Finance",
  "Aurora",
  "Avalanche",
  "Axelar",
  "Axie Infinity",
  "Aztec",
  "BabySwap",
  "Badger DAO",
  "Balancer",
  "BanklessDAO",
  "BarnBridge",
  "Base",
  "Bastion",
  "Beefy Finance",
  "Beethoven X",
  "Belt Finance",
  "Benqi",
  "Berachain",
  "Biconomy",
  "BiFi",
  "Biswap",
  "bitfari",
  "BNB Chain",
  "Boba Network",
  "Bogged Finance",
  "BONKz",
  "Bountycaster",
  "Braintrust Grants",
  "Callisto Network",
  "Canto",
  "Casper",
  "Celer Network",
  "Celo",
  "Ceramic Network",
  "Chainlink",
  "Chromia",
  "Circle",
  "CityDAO",
  "Climate Collective",
  "Clipper DEX",
  "Clover Finance",
  "clr.fund",
  "Coinbase",
  "CoinEx Smart Chain",
  "Combo",
  "Composable",
  "Compound",
  "Conflux",
  "Connext",
  "Consensys",
  "Convex Finance",
  "Coreum",
  "Cosmos Community Grants",
  "Covalent",
  "CoW Protocol",
  "Creatives DAO (NEAR)",
  "Cronos",
  "Crust Network",
  "Cube Network (Huobi)",
  "Cudos Foundation",
  "Cult DAO",
  "Curve",
  "Cypherpunk Guild (NEAR)",
  "DAOHaus",
  "DAOSquare",
  "Dark Forest",
  "Darwinia Grants",
  "Dash",
  "Decentraland",
  "Decred",
  "Defibox",
  "Dfinity (ICP)",
  "dForce",
  "Diamond DAO",
  "DIMO",
  "DODO",
  "Dopex Diamond Grants",
  "Dora Factory",
  "Dune Analytics",
  "dYdX",
  "eco",
  "Edgeware",
  "ElementFi",
  "Enjin",
  "ENS",
  "EOS",
  "Ergo",
  "ETH Prize",
  "Ethereum Foundation",
  "Euler Finance",
  "Everscale",
  "Evmos",
  "Fantom Foundation",
  "Filecoin Foundation",
  "Findora",
  "Flare",
  "Flow",
  "Flux Labs",
  "Forta",
  "Frax Finance",
  "Fuel",
  "Fuse",
  "Fusion",
  "Gains Network",
  "Game7",
  "Gari Developer DAO",
  "Gearbox",
  "Geyser",
  "Gitcoin",
  "Giveth",
  "GMX",
  "Gnosis DAO",
  "Golem Foundation",
  "Grant for the Web(Interledger)",
  "Grantshares",
  "Graph",
  "Harmony",
  "Harvest Finance",
  "Hashgraph",
  "Hedera",
  "Helium",
  "HOP Protocol",
  "HOPR",
  "Horizen",
  "Human Guild (NEAR)",
  "HUMANODE",
  "Huobi",
  "Hxro",
  "HydraDX",
  "Icon",
  "Idle DAO",
  "Illuvium",
  "Immutable X",
  "Index Coop",
  "Injective",
  "Inkubator",
  "Instadapp Lite",
  "Interchain Foundation",
  "Interlay",
  "IoTeX",
  "Juno",
  "JustLend",
  "Kadena",
  "Kava",
  "Klaytn Foundation",
  "KlimaDAO",
  "KORIS",
  "Kraken",
  "KuCoin Community Chain",
  "Kujira",
  "Kyber Network",
  "LayerZero",
  "Lens Protocol",
  "Lido (LEGO)",
  "LiquidApps",
  "Liquity",
  "Lisk",
  "Lit Protocol",
  "Livepeer",
  "LooksRare",
  "Loopring",
  "Lyra",
  "MakerDAO",
  "Mantle",
  "MAP Protocol",
  "Marinade Finance",
  "MatchboxDAO",
  "MetaCartel",
  "MetaGammaDelta",
  "Metamask Grants DAO",
  "Meter",
  "Metis",
  "MetricsDAO",
  "Metropolis (Orca)",
  "Milkomedia",
  "MilkRoad",
  "Mina Foundation",
  "Mint Fund",
  "MintBase (NEAR)",
  "Mirror Club (mClub)",
  "MolochDAO",
  "MonkeDAO",
  "Moonbeam",
  "Moonwell",
  "mStable",
  "Music Fund",
  "Near Foundation",
  "NEO",
  "Neon Foundation",
  "Nervos Network",
  "Neutron",
  "Nexus Mutual",
  "Notional",
  "Nouns DAO",
  "OAK Network",
  "Oasis Network",
  "OAX",
  "Obyte",
  "Ocean Protocol",
  "OKC",
  "Olympus",
  "Ontology",
  "OpenGrants (Ethereum)",
  "OpenLeverage",
  "OpenSea",
  "Optimism Foundation",
  "Orange DAO",
  "Origami",
  "Osmosis",
  "Paladin",
  "PancakeSwap",
  "Parity Technologies",
  "PBS Foundation Grants",
  "peaq",
  "Perpetual Protocol",
  "PIVX",
  "pNetwork",
  "Pollen",
  "Polygon Labs",
  "Polymesh",
  "PoolTogether",
  "PowerPool",
  "Prisma Finance",
  "Project Catalyst,Cardano Foundation",
  "Protocol Labs",
  "Provenance",
  "Proximity Labs (NEAR)",
  "PSE (Privacy and Scaling Explorations)",
  "Push Protocol",
  "Questbook",
  "QuickSwap",
  "Radicle",
  "Radix",
  "Raft",
  "Rally",
  "Rarible",
  "Ravencoin",
  "Redbelly",
  "Reflexer Labs",
  "REI Network",
  "Request Network",
  "Reserve",
  "Ripple",
  "RocketPool",
  "Ronin",
  "Rook",
  "Rootstock",
  "Safe",
  "Sandbox",
  "Scallop",
  "Seahorse Lang",
  "Secret Network",
  "Seed Club",
  "Sei",
  "Sevens Foundation",
  "SKALE",
  "Social Alpha Foundation",
  "Solana Foundation",
  "Sovryn",
  "SpaceID",
  "Spiral",
  "SpookySwap",
  "Stacks Foundation",
  "StarCoin",
  "Starknet",
  "Stellar Development Foundation",
  "Streamr Network",
  "Strike Finance",
  "Sui Foundation",
  "Superfluid",
  "SuperRare",
  "Superteam",
  "SushiSwap",
  "Swarm Foundation",
  "Synapse",
  "Synthetix",
  "Syscoin",
  "Tableland",
  "Taiko",
  "Tally",
  "Tea Protocol",
  "TegroFi",
  "Telos",
  "Tempus",
  "Tezos Foundation",
  "The LAO",
  "Thundercore",
  "Token Engineering Commons",
  "Tokenlon",
  "TON",
  "Toucan",
  "Tron",
  "Tulip",
  "Ubiquity DAO",
  "UMA",
  "Uniswap Foundation",
  "Unlock Protocol",
  "Unstoppable Domains",
  "Valist",
  "Vechain",
  "veFunder (Curve)",
  "Vega",
  "Velas",
  "Venus",
  "Vulcan Forged",
  "Waves",
  "Web3 Foundation",
  "WhiteBIT",
  "Worldcoin Foundation",
  "Wormhole xGrants",
  "XMTP",
  "XPR Network",
  "XRPL Grants",
  "yearn.finance",
  "zCash",
  "Zebec Protocol",
  "ZetaChain",
  "Zilliqa",
];

const networkImages: Record<
  string,
  {
    light: string;
    dark: string;
  }
> = {
  aleo: {
    light: "/images/networks/aleo-light.svg",
    dark: "/images/networks/aleo-dark.svg",
  },
  "aleph zero": {
    light: "/images/networks/aleph-zero-light.svg",
    dark: "/images/networks/aleph-zero-dark.svg",
  },
  bitcoin: {
    light: "/images/networks/bitcoin.svg",
    dark: "/images/networks/bitcoin.svg",
  },
  cardano: {
    light: "/images/networks/cardano.svg",
    dark: "/images/networks/cardano.svg",
  },
  "cosmos/ibc": {
    light: "/images/networks/cosmos.svg",
    dark: "/images/networks/cosmos.svg",
  },
  evm: {
    light: "/images/networks/ethereum.svg",
    dark: "/images/networks/ethereum.svg",
  },
  farcaster: {
    light: "/images/networks/farcaster.svg",
    dark: "/images/networks/farcaster.svg",
  },
  near: {
    light: "/images/networks/near.svg",
    dark: "/images/networks/near.svg",
  },
  nouns: {
    light: "/images/networks/nouns.jpeg",
    dark: "/images/networks/nouns.jpeg",
  },
  polkadot: {
    light: "/images/networks/polkadot.svg",
    dark: "/images/networks/polkadot.svg",
  },
  ripple: {
    light: "/images/networks/ripple.svg",
    dark: "/images/networks/ripple.svg",
  },
  solana: {
    light: "/images/networks/solana.svg",
    dark: "/images/networks/solana.svg",
  },
  stellar: {
    light: "/images/networks/stellar-light.svg",
    dark: "/images/networks/stellar-dark.svg",
  },
  ton: { light: "/images/networks/ton.svg", dark: "/images/networks/ton.svg" },
  tezos: {
    light: "/images/networks/tezos.svg",
    dark: "/images/networks/tezos.svg",
  },
  tron: {
    light: "/images/networks/tron.svg",
    dark: "/images/networks/tron.svg",
  },
  zcash: {
    light: "/images/networks/zcash.svg",
    dark: "/images/networks/zcash.svg",
  },
};

const ecosystems = [
  "Aave",
  "Akash",
  "Alchemy",
  "Algorand",
  "Aptos",
  "Aragon",
  "Arbitrum",
  "Arcana",
  "Astar",
  "Aurora",
  "Avalanche",
  "Base",
  "Berachain",
  "Binance Smart Chain",
  "Bitcoin",
  "Boba Network",
  "Callisto Network",
  "Canto",
  "Cardano",
  "Casper",
  "Celo",
  "Chainlink",
  "CoinEx Smart Chain",
  "Compound",
  "Conflux",
  "Coreum",
  "Cosmos",
  "Cronos",
  "Dash",
  "Decentraland",
  "Decred",
  "Dfinity",
  "Edgeware",
  "EOSIO",
  "Ethereum",
  "Fantom",
  "Farcaster",
  "Findora",
  "Flare",
  "Flow",
  "Fuel",
  "Gnosis Chain",
  "Harmony",
  "Hedera",
  "Helium",
  "Horizen",
  "Interlay",
  "IoTeX",
  "Kava",
  "Klaytn",
  "KuCoin",
  "Lisk",
  "Lit Protocol",
  "Metis",
  "Mina",
  "Moonbeam",
  "Moonriver",
  "Near",
  "NEO",
  "Neon",
  "Nervos Network",
  "OAK Network",
  "Oasis Network",
  "Obyte",
  "OKC",
  "Optimism",
  "PIVX",
  "Polkadot",
  "Polygon",
  "Radix",
  "Ravencoin",
  "REI Network",
  "Ripple",
  "Ronin",
  "Solana",
  "Sovryn",
  "Stacks",
  "StarCoin",
  "Stellar",
  "Sui",
  "Syscoin",
  "Telos",
  "Tezos",
  "Thundercore",
  "TON",
  "Tron",
  "Uniswap",
  "Vechain",
  "Velas",
  "Waves",
  "XPR Network",
  "zCash",
  "ZetaChain",
  "Zilliqa",
];
const categories = [
  "DEX",
  "DeFi",
  "GameFi",
  "NFT",
  "Lend/Borrow",
  "Communities",
  "Research",
  "Yield Farming",
  "Infrastructure",
];
const grantTypes = [
  "Direct Grants",
  "Bounties",
  "Retro Funding",
  "Quadratic Funding",
];
const platformsUsed = [
  "Gitcoin",
  "Questbook",
  "Charmverse",
  "GitHub",
  "Notion",
  "Custom",
];

const grantSizes = [0, 250000];

export const registryHelper = {
  networks,
  organizations,
  ecosystems,
  categories,
  grantTypes,
  grantSizes,
  networkImages,
  platformsUsed,
};
